//For user
export const CREAT_ORDER_START = "CREAT_ORDER_START";
export const CREAT_ORDER_SUCCESS = "CREAT_ORDER_SUCCESS";
export const CREAT_ORDER_FAIL = "CREAT_ORDER_FAIL";

export const GET_MY_ORDER_START = "GET_MY_ORDER_START";
export const GET_MY_ORDER_SUCCESS = "GET_MY_ORDER_SUCCESS";
export const GET_MY_ORDER_FAIL = "GET_MY_ORDER_FAIL";

export const GET_MY_ORDER_DETAILS_START = "GET_MY_ORDER_DETAILS_START";
export const GET_MY_ORDER_DETAILS_SUCCESS = "GET_MY_ORDER_DETAILS_SUCCESS";
export const GET_MY_ORDER_DETAILS_FAIL = "GET_MY_ORDER_DETAILS_FAIL";

//For Admin
export const GET_ALL_ORDER_START = "GET_ALL_ORDER_START";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAIL = "GET_ALL_ORDER_FAIL";

export const UPDATE_ORDER_START = "UPDATE_ORDER_START";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";
export const UPDATE_ORDER_RESET = "UPDATE_ORDER_RESET";

export const DELETE_ORDER_START = "DELETE_ORDER_START";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const DELETE_ORDER_RESET = "DELETE_ORDER_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
