export const PRODUCT_START = "PRODUCT_START";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_FAIL = "PRODUCT_FAIL";

export const PRODUCT_DETAILS_START = "PRODUCT_DETAILS_START";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const REVIEW_START = "REVIEW_START";
export const REVIEW_SUCCESS = "REVIEW_SUCCESS";
export const REVIEW_RESET = "REVIEW_RESET";
export const REVIEW_FAIL = "REVIEW_FAIL";

export const ADMIN_PRODUCT_START = "ADMIN_PRODUCT_START";
export const ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS";
export const ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL";

//For Admin-------------------------------------------------------
export const ADMIN_PRODUCT_CREATE_START = "ADMIN_PRODUCT_CREATE_START";
export const ADMIN_PRODUCT_CREATE_SUCCESS = "ADMIN_PRODUCT_CREATE_SUCCESS";
export const ADMIN_PRODUCT_CREATE_FAIL = "ADMIN_PRODUCT_CREATE_FAIL";
export const ADMIN_PRODUCT_CREATE_RESET = "ADMIN_PRODUCT_CREATE_RESET";

export const ADMIN_PRODUCT_DELETE_START = "ADMIN_PRODUCT_DELETE_START";
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS";
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL";
export const ADMIN_PRODUCT_DELETE_RESET = "ADMIN_PRODUCT_DELETE_RESET";

export const ADMIN_PRODUCT_UPDATE_START = "ADMIN_PRODUCT_UPDATE_START";
export const ADMIN_PRODUCT_UPDATE_SUCCESS = "ADMIN_PRODUCT_UPDATE_SUCCESS";
export const ADMIN_PRODUCT_UPDATE_FAIL = "ADMIN_PRODUCT_UPDATE_FAIL";
export const ADMIN_PRODUCT_UPDATE_RESET = "ADMIN_PRODUCT_UPDATE_RESET";

export const ALL_REVIEW_START = "ALL_REVIEW_START";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_START = "DELETE_REVIEW_START";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";

export const CLEAR_ERROR = "CLEAR_ERROR";
